### ISSUE TITLE
QuickBooks with AuthCode strategy doesn't like client_id with basic auth

### ISSUE THREAD

**Issue by michaelst** [ueberauth/oauth2#140]
Not sure if client_id was intentionally left in the auth code request alongside the Basic auth, but it does break with QuickBooks, doesn't appear to affect any other of the integrations I have connected with oauth. Thought I would bring it up just in case anyone else runs into that issue. 

For now I implemented a delete_param function to remove it 
```
  def delete_param(%{params: params} = client, key) do
    %{client | params: Map.delete(params, "#{key}")}
  end

  def get_token(client, params, headers) do
    client
    |> put_header("accept", "application/json")
    |> OAuth2.Strategy.AuthCode.get_token(params, headers)
    |> delete_param(:client_id)
  end

**Comment by scrogson** [comment]
Thanks for the report @michaelst

**Comment by sheharyarn** [comment]
Been having the same issue. I cover it in more detail in #142.

**Comment by kplattret** [comment]
I had a similar issue with the Battle.net API and this solved it. Thanks!
