### ISSUE TITLE
Issue with refresh_token

### ISSUE THREAD

**Issue by sircon** [ueberauth/oauth2#143]
I'm having issues with refreshing a Spotify token using the OAuth2 library.

This is the debug I'm getting.
```
[debug]   OAuth2 Provider Request
  url: "https://accounts.spotify.com/api/token"
  method: :post
  headers: [{"accept", "application/x-www-form-urlencoded"}, {"content-type", "application/x-www-form-urlencoded"}, {"authorization", "Basic OT...DA="}]
  body: "grant_type=refresh_token&refresh_token=AQ...1Lg"
  req_opts: []
```

Doing the same request using Curl or Postman works alright, but via OAuth2 always gives a 406...

This would be the Curl equivalent:
```
curl -X "POST" "https://accounts.spotify.com/api/token" \
     -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' \
     -u '9...1:1...0' \
     --data-urlencode "grant_type=refresh_token" \
     --data-urlencode "refresh_token=AQ...A1Lg"
```

I wonder what am I doing wrong.

This is my last attempt following the Readme:
```
refresh_client = OAuth2.Client.new([
  strategy: OAuth2.Strategy.Refresh,
  client_id: System.get_env("VF_SPOTIFY_CLIENT_ID"),
  client_secret: System.get_env("VF_SPOTIFY_CLIENT_SECRET"),
  token_url: "https://accounts.spotify.com/api/token",
  params: %{"refresh_token" => refresh_token}
])

refresh_client = OAuth2.Client.get_token!(refresh_client)
```

I'm using OAuth2 version 2.0.0, in case this is relevant.

Thanks in advance for the help,
Miguel

**Comment by sickill** [comment]
I had similar problem (406 error), and solved it by overriding `accept` header when constructing client:

```
OAuth2.Client.new([
  strategy: ...,
  ...,
  headers: [{"accept", "application/json,application/x-www-form-urlencoded"}]
])
```

**Comment by thatcherhubbard** [comment]
This bit me too, but I don't see anywhere in the repo where it explicitly sets that value on the `Accept` header, just `Content-Type`.  Should the `OAuth2.Client.new` function have a default that sets `Accept` to `*/*`?

**Comment by sircon** [comment]
Thanks @sickill, I will give it a try. If it works then it seems that is missing the accepts `application/json` header as it has the other one.
