### ISSUE TITLE
Defaults to application/json when content-type header is not present

### ISSUE THREAD

**Issue by sheharyarn** [ueberauth/oauth2#158]
Thanks for the amazing library! I came across a bug and wanted to report:

The OAuth2 library [defaults to](https://github.com/scrogson/oauth2/blob/b5cdbdb475a2ffebd0f48e3289f64cfcdd67dfb9/lib/oauth2/util.ex#L11-L21) `application/json` response type when no `content-type` header is present. Since the `Response` module calls [`serializer.decode!(body)`](https://github.com/scrogson/oauth2/blob/b5cdbdb475a2ffebd0f48e3289f64cfcdd67dfb9/lib/oauth2/response.ex#L52-L54), this causes an exception (as expected) since the body being decoded is probably not JSON.

The default should probably be `text/plain` and it should return the body as-is. On a side note, you should probably use [Plug's implementation](https://hexdocs.pm/plug/Plug.Conn.Utils.html#content_type/1) of extracting content-type, so it correctly parses even when there is extra metadata attached.

(For reference, I'm having this issue with the Zendesk API where some API responses don't have the content-type header).

**Comment by andyleclair** [comment]
I'm here to +1 this, we've had an issue with Auth0 today and we've run into the same issue. I'm happy to contribute some code if you would like help on this!

**Comment by yordis** [comment]
I agree with this, but I am not sure how much of a breaking change would be and the potential downsides of it, I think it will be prudent to try to have some answer for such concern or at the very least a backup plan or guidelines for peeps facing the potential issue with it.

@ueberauth/developers any thoughts on the subject?
