### ISSUE TITLE
PKCE flow?

### ISSUE THREAD

**Issue by kayuapi** [ueberauth/oauth2#161]
Hi,

I was just wondering if PKCE flow belongs to the scope of this library? If so, is pull request welcomed? (might do it when I have free time)

ref: https://oauth.net/2/pkce/

**Comment by arturjzapater** [comment]
If this library doesn't support it, does https://github.com/ueberauth/ueberauth support it?

**Comment by saneery** [comment]
bump

**Comment by adamcstephens** [comment]
oidcc can do PKCE and has a ueberauth plugin https://github.com/erlef/oidcc
