### ISSUE TITLE
I want to curse and curse. A lot

### ISSUE THREAD

**Issue by GildedHonour** [ueberauth/oauth2#168]
### Steps to Reproduce

When it comes to Twitter API, there's a bug in your lib. If I hadn't fixed a URL manually, I'd perhaps have spent a few additional days cursing Twitter API and wasting my time. Instead I'm cursing your library.

Curse-curse

### Expected Result

success

### Actual Result

failure

**Comment by korczis** [comment]
I feel your pain and frustration now. So, can you share how can I workaround it?*
